import Head from "next/head";
import CodeInput from "@/components/CodeInput";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>코오드 리뷰 봇</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6389820476496669"
          crossOrigin="anonymous"
        />
      </Head>
      <div className="flex h-screen flex-col gap-4 bg-slate-700">
        <CodeInput />
        <footer className="mb-4 text-center text-white">
          © 2023. All rights reserved by{" "}
          <Link target="_blank" href="https://github.com/Jeremy-Kr">
            Jeremy-Kr
          </Link>
        </footer>
      </div>
    </>
  );
}
